### ISSUE TITLE
Fatal exception (28) after flashing

### ISSUE THREAD

**Issue by GTP95** [mehdilauters/esp8266-reverse-socks5#2]
Hello, 
I followed the instructions in the readme to try to flash a nodemcu clone with an esp-12N mounted on it (probably just an esp-12E with a different antenna pcb trace), but right after executing "make flash" my module gave the following endlessly repeated output (read through a serial terminal):
`Fatal exception (28): 
epc1=0x4000228b, epc2=0x00000000, epc3=0x00000000, excvaddr=0x000000b5, depc=0x00000000
`
After a reset it outputted the usual seemingly-random output and then nothing more. What could have gone wrong?
Thanks for your help.

EDIT: I updated esptool to the last available version on pip and now after reset I don't get any intelligible output.

**Comment by mehdilauters** [comment]
Hi,
I guess it should be related to the freeRTOS version. I didn't play with this project for a long time so I can't give you more information but maybe you should try to downgrade to an oldest freeRTOS version ( from 2 years ago ).
I already tested this project on an ESP12-E so the target itself should not be a problem.
If I get some time to test it I will let you know

**Comment by mehdilauters** [comment]
Using the following docker
https://hub.docker.com/r/bschwind/esp-open-rtos/
and the following command line
````
docker run --rm -it --privileged -e "ESPBAUD=115200" -v /dev/bus/usb:/dev/bus/usb -v $PWD:/home/esp/esp-open-rtos/examples/project esp-open-rtos /bin/bash
make flash
````
The esp12e boots as it should so you may have an issue elsewhere (flash size?, power?)
